package Assignment_5;
import java.io.*;
import java.net.*;
import java.util.*;

public class Server {
    public static void main(String[] args) throws IOException {
        ServerSocket serverSocket = new ServerSocket(1234);
        System.out.println("Server started. Waiting for clients...");

        int randomNumber = new Random().nextInt(101); // Generate random number between 0 and 100
        System.out.println("Random number generated by the server: " + randomNumber);

        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                sendToAllClients("time out");
                System.exit(0);
            }
        }, 180000); // 3 minutes timeout

        while (true) {
            Socket clientSocket = serverSocket.accept();
            System.out.println("Client connected: " + clientSocket);

            ClientHandler clientHandler = new ClientHandler(clientSocket, randomNumber);
            clientHandler.start();
        }
    }

    private static List<PrintWriter> clientOutputStreams = new ArrayList<>();

    public static void addClientOutputStream(PrintWriter out) {
        clientOutputStreams.add(out);
    }

    public static void removeClientOutputStream(PrintWriter out) {
        clientOutputStreams.remove(out);
    }

    public static void sendToAllClients(String message) {
        for (PrintWriter writer : clientOutputStreams) {
            writer.println(message);
            writer.flush();
        }
    }
}
